language: node_js

node_js:
- 6.1.0

branches:
  only:
  - develop

services:
- mongodb

before_script:
- sleep 5
- npm install -g gulp jspm pm2 jasmine
- export FOO=this is foo

script:
- source run-tests.sh
